### ISSUE TITLE
Link to Vue.js example on homepage is not working

### ISSUE THREAD

**Issue by rgtk** [Palindrom/palindrom.github.io#1]
Vue.js link in "Plays well with" section doesn't target proper resource. Clicking on it, opens current page in new tab.

URL: https://palindrom.github.io/#/
UA: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36"

**Comment by alshakero** [comment]
Thank you so much for reporting. Fixed now.
